## ODOC Public Inmate Data


To use this notebook, download the data published [here](http://doc.publishpath.com/odoc-public-inmate-data). Unzip the file and place the files in a subdirectory called 'data'.

The set of files includes a ReadMe.txt which describes the files and their fixed formats. The first sections of this notebook show description of each file and how to import it into pandas dataframes.  NOTE: the widths variable differ slighty from the description to handle some difference in the data.

In [24]:
import pandas as pd

## Schedule A - Profile Data Layout
 ```
 =======================================================
 Name                            Null?    Type
 ------------------------------- -------- ----
 DOC_NUM                         NOT NULL NUMBER(10)
 LAST_NAME                                VARCHAR2(30)
 FIRST_NAME                               VARCHAR2(30)
 MIDDLE_NAME                              VARCHAR2(30)
 SUFFIX                                   VARCHAR2(5)
 LAST_MOVE_DATE                           DATE 'DD-MMM-YY' (9)
 FACILITY                                 VARCHAR2(40)
 BIRTH_DATE                               DATE 'DD-MMM-YY' (9)
 SEX                                      VARCHAR2(1)
 RACE                                     VARCHAR2(40)
 HAIR                                     VARCHAR2(40)
 HEIGHT_FT                                VARCHAR2(2)
 HEIGHT_IN                                VARCHAR2(2)
 WEIGHT                                   VARCHAR2(4)
 EYE                                      VARCHAR2(40)
 STATUS                                   VARCHAR2(10)
 ```

In [25]:
file = 'data/Vendor_Profile_Sample_Text.dat'

# uncomment this line to use the full dataset
# file = 'data/Vendor_Profile_Extract_Text.dat'

names = [
    "DOC_NUM"       
    ,"LAST_NAME"     
    ,"FIRST_NAME"    
    ,"MIDDLE_NAME"   
    ,"SUFFIX"        
    ,"LAST_MOVE_DATE"
    ,"FACILITY"      
    ,"BIRTH_DATE"    
    ,"SEX"           
    ,"RACE"          
    ,"HAIR"          
    ,"HEIGHT_FT"     
    ,"HEIGHT_IN"     
    ,"WEIGHT"        
    ,"EYE"           
    ,"STATUS"
]
widths = [
    11,
    30,
    30,
    30,
    5,
    9,
    40,
    9,
    1,
    40,
    40,
    2,
    2,
    4,
    40,10
]

df = pd.read_fwf(file, 
    header=None,
    widths=widths,
    names=names)
                 
df

,DOC_NUM,LAST_NAME,FIRST_NAME,MIDDLE_NAME,SUFFIX,LAST_MOVE_DATE,FACILITY,BIRTH_DATE,SEX,RACE,HAIR,HEIGHT_FT,HEIGHT_IN,WEIGHT,EYE,STATUS
0,400000,KANNADY,CARL,NaN,NaN,NaN,INACTIVE,06-SEP-56,M,WHITE,BROWN,6,0,210,GREEN,Inactive
1,400001,SMITH,ADOLPHUS,HOWARD,NaN,NaN,INACTIVE,09-APR-71,M,BLACK,BLACK,5,7,155,BROWN,Inactive
2,400002,LE,DAVID,SMITH,NaN,NaN,INACTIVE,26-AUG-80,M,ASIAN,BLACK,5,6,150,BROWN,Inactive
3,400003,PHILLIPS,CLINT,ALLEN,NaN,NaN,INACTIVE,24-AUG-75,M,WHITE,BROWN,5,7,162,BROWN,Inactive
4,400005,COLEMAN,JOEL,NaN,NaN,NaN,INACTIVE,15-JAN-67,M,WHITE,BLONDE,5,7,150,BROWN,Inactive
5,400006,SMITH,DANIEL,DUANE,NaN,30-MAY-08,INACTIVE,14-DEC-74,M,WHITE,BROWN,6,3,205,BROWN,Inactive
6,400007,HILL,MICHAEL,NaN,NaN,NaN,INACTIVE,24-OCT-55,M,WHITE,RED,5,8,180,BROWN,Inactive
7,400009,MCLAIN,JOSEPH,NaN,NaN,NaN,INACTIVE,12-DEC-76,M,WHITE,RED,5,3,145,BLUE,Inactive
8,400014,BLEDSOE,TONY,LEE,NaN,13-MAY-02,INACTIVE,24-APR-77,M,WHITE,BLONDE,6,0,150,HAZEL,Inactive
9,400019,BEVENS,KAREN,ANNETTE,NaN,NaN,INACTIVE,07-OCT-61,F,WHITE,BROWN,5,2,140,BLUE,Inactive
10,400021,CLARK,JASON,DARNELL,NaN,04-JUN-10,INACTIVE,25-APR-80,M,BLACK,BLACK,5,9,176,BROWN,Inactive
11,400029,BROWN,CHRISTOPHER,NaN,NaN,NaN,INACTIVE,04-OCT-79,M,BLACK,BLACK,5,9,187,BROWN,Inactive
12,400031,EATON,RONALD,GENE,NaN,NaN,INACTIVE,07-FEB-52,M,WHITE,BROWN,5,10,230,BROWN,Inactive
13,400033,ENGLISH,SHERI,SUE,NaN,20-MAY-04,INACTIVE,07-NOV-66,F,WHITE,BROWN,5,7,125,BLUE,Inactive
14,400037,TUCKER,KEVIN,B,NaN,NaN,INACTIVE,12-SEP-72,M,WHITE,BLONDE,5,7,140,BLUE,Inactive
15,400039,DIOSDADO,JUAN,RAMIRES,NaN,29-APR-03,INACTIVE,13-JUN-74,M,HISPANIC,BLACK,5,3,158,BROWN,Inactive
16,400041,GREEN,CHARLENE,M,NaN,NaN,INACTIVE,16-SEP-61,F,BLACK,BLACK,5,0,185,BROWN,Inactive
17,400045,FIELDS,KIRK,WAYNE,NaN,14-JAN-11,INACTIVE,08-NOV-59,M,BLACK,BLACK,6,2,240,BROWN,Inactive
18,400049,FOX,TENIKA,YASHEA,NaN,NaN,INACTIVE,26-AUG-81,F,BLACK,BLACK,5,3,180,NaN,Inactive
19,400052,FIELDS,JAMES,ALRED,NaN,05-AUG-08,INACTIVE,09-NOV-65,M,BLACK,BLACK,5,11,165,BLACK,Inactive
20,400056,JAMES,DARRYL,R,JR,NaN,INACTIVE,10-SEP-80,M,BLACK,BLACK,5,6,129,BROWN,Inactive
21,400058,DILLMAN,WILLIAM,MATTHEW,NaN,NaN,INACTIVE,13-SEP-60,M,WHITE,BROWN,5,9,160,HAZEL,Inactive
22,400059,ALLERMANN,ROBERT,BRIAN,NaN,NaN,INACTIVE,15-SEP-63,M,WHITE,BROWN,6,0,160,BROWN,Inactive
23,400069,THACH,LUCAS,GABRIEL,NaN,01-OCT-03,INACTIVE,22-JAN-82,M,WHITE,BROWN,5,9,165,HAZEL,Inactive
24,400088,LEE,JENNIFER,SUE LYNN,NaN,24-DEC-02,TULSA COUNTY DISTRICT,26-SEP-72,F,WHITE,BLONDE,5,1,134,BLUE,Active
25,400092,ALLEN,JACKIE,LEWIS,NaN,NaN,INACTIVE,21-SEP-66,M,WHITE,BROWN,5,10,165,BROWN,Inactive
26,400094,KITTRELL,DAVID,CHRISTOPHER,NaN,26-FEB-19,DAVIS CORRECTIONAL FACILITY-HOLDENVILLE,05-APR-82,M,WHITE,BROWN,5,8,161,BLUE,Active
27,400095,LEWALLEN,ELAINE,Y,NaN,18-JUN-04,INACTIVE,20-JUN-71,F,WHITE,BROWN,5,7,121,GREEN,Inactive
28,400096,ELLETT,RACE,LEE,NaN,24-DEC-02,INACTIVE,08-NOV-80,M,WHITE,BROWN,5,8,182,BROWN,Inactive
29,400097,THOMAS,DUSTIN,NaN,NaN,28-FEB-18,OKLAHOMA STATE PENITENTIARY,29-DEC-78,M,NATIVE AMERICAN,BLACK,5,7,204,BROWN,Active
30,400098,MILLER,MICHAEL,SHANE,NaN,25-NOV-09,INACTIVE,28-FEB-68,M,WHITE,BROWN,5,10,231,BLUE,Inactive
31,400099,STEPHENS,GARY,K,NaN,01-SEP-17,NORTH FORK CORRECTIONAL CENTER,11-FEB-50,M,WHITE,BROWN,5,6,200,BROWN,Active
32,400100,MISER,SHANE,L,NaN,29-APR-02,INACTIVE,14-AUG-74,M,WHITE,BLONDE,6,1,176,BLUE,Inactive

## Schedule B - Alias Data Layout
```
=======================================================
 Name                            Null?    Type
 ------------------------------- -------- ----
 DOC_NUM                         NOT NULL NUMBER(10)
 LAST_NAME                                VARCHAR2(30)
 FIRST_NAME                               VARCHAR2(30)
 MIDDLE_NAME                              VARCHAR2(30)
 SUFFIX                                   VARCHAR2(5)
```

In [27]:
file = 'data/Vendor_Alias_Sample_Text.dat'

# uncomment this line to use the full dataset
# file = 'data/Vendor_Alias_Extract_Text.dat'

names = ["DOC_NUM", "LAST_NAME", "FIRST_NAME", "MIDDLE_NAME","SUFFIX"
]

widths = [ 11, 30, 30, 30, 5]

df = pd.read_fwf(file, 
    header=None,
    widths=widths,
    names=names)
                 
df

    DOC_NUM  LAST_NAME   FIRST_NAME  MIDDLE_NAME SUFFIX
0    400000    KANNADY         CARL          NaN    NaN
1    400001      SMITH     ADOLPHUS       HOWARD    NaN
2    400002         LE        DAVID        SMITH    NaN
3    400003   PHILLIPS        CLINT        ALLEN    NaN
4    400005    COLEMAN         JOEL          NaN    NaN
5    400006      SMITH       DANIEL        DUANE     JR
6    400006      SMITH       DANIEL        DUANE    NaN
7    400006      SMITH       DANIEL      DUANEJR    NaN
8    400007       HILL      MICHAEL          NaN    NaN
9    400009     MCLAIN       JOSEPH          NaN    NaN
10   400014    BLEDSOE        TOMMY          LEE    NaN
11   400014    BLEDSOE         TONY           CL    NaN
12   400014    BLEDSOE         TONY      COLEMAN    NaN
13   400014    BLEDSOE         TONY   COLMAN LEE    NaN
14   400014    BLEDSOE         TONY          LEE    NaN
15   400019     BEVENS        KAREN      ANNETTE    NaN
16   400021      CLARK        JASON      DARNELL    NaN
17   400029      BROWN  CHRISTOPHER          NaN    NaN
18   400031      EATON       RONALD         GENE    NaN
19   400033    ENGLISH        SHERI          SUE    NaN
20   400033      TIVIS        SHERI          SUE    NaN
21   400037     TUCKER        KEVIN            B    NaN
22   400039   DIOSDADO         JUAN       MANUEL    NaN
23   400039   DIOSDADO         JUAN      RAMIRES    NaN
24   400041      GREEN     CHARLEEN            M    NaN
25   400041      GREEN     CHARLENE            M    NaN
26   400045     FIELDS         KIRK            W    NaN
27   400045     FIELDS         KIRK        WAYNE    NaN
28   400049        FOX       TENIKA       YASHEA    NaN
29   400052     FIELDS        JAMES            A    NaN
30   400052     FIELDS        JAMES       ALFRED    NaN
31   400052     FIELDS        JAMES        ALRED    NaN
32   400056      JAMES       DARRYL            R     JR
33   400058    DILLMAN      WILLIAM      MATTHEW    NaN
34   400059   ALLERMAN       ROBERT          NaN    NaN
35   400059  ALLERMANN       ROBERT        BRIAN    NaN
36   400069      THACH        LUCAS      GABRIEL    NaN
37   400069      THACH        LUCUS      GABRIEL    NaN
38   400069     THATCH        LUCAS          NaN    NaN
39   400088    BLEDSOE     JENNIFER       SUELYN    NaN
40   400088        LEE      JENIFER       SUELYN    NaN
41   400088        LEE     JENNIFER     SUE LYNN    NaN
42   400092      ALLEN       JACKIE        LEWIS    NaN
43   400094   KITTRELL        DAVID  CHRISTOPHER    NaN
44   400095   LEWALLEN       ELAINE            Y    NaN
45   400095   LEWALLEN       ELAINE       YVONNE    NaN
46   400095     MILLER       ELAINE          NaN    NaN
47   400096     ELLETT         RACE          LEE    NaN
48   400096       RACE       ELLETT          LEE    NaN
49   400097     THOMAS       DUSTIN            M    NaN
50   400097     THOMAS       DUSTIN          NaN    NaN
51   400098     MILLER      MICHAEL        SHANE    NaN
52   400098     MILLER      MICHAEL       SHAYNE    NaN
53   400098     MILLER         MIKE            S    NaN
54   400099   STEPHENS         GARY            K    NaN
55   400099   STEPHENS          RED          NaN    NaN
56   400100      MISER        SHANE            L    NaN
57   400100      MIZER        SHANE          LEE    NaN

## Schedule C - Sentence Data Layout
```
=======================================================
Incarcerated_Term_In_Years = 9999 indicates a death sen
tence

Incarcerated_Term_In_Years = 8888 indicates a life with
out parole sentence

Incarcerated_Term_In_Years = 7777 indicates a life sent
ence
=======================================================
 Name                            Null?    Type
 ------------------------------- -------- ----
 DOC_NUM                         NOT NULL NUMBER(10)
 STATUTE_CODE                    NOT NULL VARCHAR2(40)
 SENTENCING_COUNTY                        VARCHAR2(40)
 JS_DATE                                  DATE 'YYYYMMDD' (8)
 CRF_NUMBER                               VARCHAR2(40)
 INCARCERATED_TERM_IN_YEARS               NUMBER(10,2)
 PROBATION_TERM_IN_YEARS                  NUMBER(10,2)
 ```

In [30]:
file = 'data/Vendor_sentence_Sample_Text.dat'

# uncomment this line to use the full dataset
# file = 'data/Vendor_sentence_Extract_Text.dat'


names =[
    "DOC_NUM",                   
    "STATUTE_CODE",              
    "SENTENCING_COUNTY",         
    "JS_DATE",                   
    "CRF_NUMBER",                
    "INCARCERATED_TERM_IN_YEARS",
    "PROBATION_TERM_IN_YEARS"
]

widths = [
    10,
    40,
    40,
    10,
    40,
    13,
    13
]

df = pd.read_fwf(file, 
    header=None,
    widths=widths,
    names=names)
                 
df

,DOC_NUM,STATUTE_CODE,SENTENCING_COUNTY,JS_DATE,CRF_NUMBER,INCARCERATED_TERM_IN_YEARS,PROBATION_TERM_IN_YEARS
0,40000,021-1123.A,ARKANSAS JURISDICTION,05-FEB-97,1996-2007,NaN,9.95
1,40000,121-1435,COLORADO JURISDICTION,30-APR-01,00CR668-18,NaN,3.00
2,40000,221-1731,OKLAHOMA COUNTY COURT,15-JUN-01,2000-6699,NaN,1.00
3,40000,321-797,TEXAS JURISDICTION,30-APR-01,"B28,824",NaN,3.00
4,40000,521-1713,MUSKOGEE COUNTY COURT,19-JUN-01,1999-1078,NaN,3.00
5,40000,621-1544,WASHINGTON COUNTY COURT,21-JUN-01,1999-171,NaN,5.00
6,40000,621-1544,WASHINGTON COUNTY COURT,19-JUN-06,1999-171,NaN,5.00
7,40000,615-765.3,TULSA COUNTY COURT,27-OCT-04,2004-2092,8.0,NaN
8,40000,615-765.3,TULSA COUNTY COURT,27-OCT-04,2004-2182,8.0,NaN
9,40000,621-1542,WASHINGTON COUNTY COURT,21-JUN-01,99-171,2.0,3.00
10,40000,647-11-902.C,TULSA COUNTY COURT,22-MAY-18,CF-2018-40,NaN,4.00
11,40000,621-1544,WASHINGTON COUNTY COURT,21-JUN-01,1999-171,NaN,10.00
12,40000,721-1705,MUSKOGEE COUNTY COURT,21-JUN-01,2001-309,NaN,1.00
13,40000,721-1713,MUSKOGEE COUNTY COURT,21-JUN-01,2001-309,NaN,1.00
14,40000,963-2-402,MUSKOGEE COUNTY COURT,18-JUN-01,2000-73,NaN,3.00
15,40000,963-2-405,MUSKOGEE COUNTY COURT,18-JUN-01,2000-73,NaN,3.00
16,40000,921-853,MUSKOGEE COUNTY COURT,18-JUN-01,2000-73,NaN,3.00
17,40000,963-2-402,MUSKOGEE COUNTY COURT,01-JUN-04,2000-73,NaN,10.00
18,40000,921-455,MUSKOGEE COUNTY COURT,01-JUN-04,2003-69,NaN,10.00
19,40001,463-2-402,TULSA COUNTY COURT,03-AUG-01,2001-539,2.0,NaN
20,40001,463-2-402,TULSA COUNTY COURT,03-AUG-01,2001-2958,3.0,NaN
21,40001,463-2-402,TULSA COUNTY COURT,13-MAY-02,CF-2001-2958,NaN,0.83
22,40001,463-2-402,TULSA COUNTY COURT,10-FEB-04,2003-4175,NaN,NaN
23,40001,963-2-402,TULSA COUNTY COURT,29-AUG-01,2001-41,2.0,NaN
24,40002,121-1289.18,MUSKOGEE COUNTY COURT,12-JUN-01,2000-826,NaN,3.00
25,40002,163-2-402,MUSKOGEE COUNTY COURT,18-FEB-03,2001-1077,NaN,5.00
26,40002,163-2-402,MUSKOGEE COUNTY COURT,01-NOV-04,2003-778,NaN,5.00
27,40002,163-2-401,MUSKOGEE COUNTY COURT,21-APR-08,2001-1077,5.0,NaN
28,40002,163-2-402,MUSKOGEE COUNTY COURT,21-APR-08,2003-778,5.0,NaN
29,40002,163-2-401,MUSKOGEE COUNTY COURT,21-APR-08,2004-946,5.0,15.00
...,...,...,...,...,...,...,...
103,40009,621-1704,GARVIN COUNTY COURT,28-SEP-01,2001-143,5.0,NaN
104,40009,621-1321.7,GARVIN COUNTY COURT,28-SEP-01,2001-144,5.0,NaN
105,40009,621-1541.2,CRAIG COUNTY COURT,05-NOV-01,99-84,4.0,5.00
106,40009,621-1704,GARVIN COUNTY COURT,24-DEC-02,2001-89,NaN,0.85
107,40009,621-1704,GARVIN COUNTY COURT,24-DEC-02,2001-90,NaN,0.85
108,40009,621-1704,GARVIN COUNTY COURT,24-DEC-02,2001-88,NaN,0.85
109,40009,621-1321.7,GARVIN COUNTY COURT,24-DEC-02,2001-144,NaN,0.85
110,40009,621-1704,GARVIN COUNTY COURT,24-DEC-02,2001-143,NaN,0.85
111,40009,621-1321.7,GARVIN COUNTY COURT,24-DEC-02,2001-140,NaN,0.85
112,40009,621-1704,GARVIN COUNTY COURT,24-DEC-02,2001-139,NaN,0.85
113,40009,659-1512,GARVIN COUNTY COURT,24-DEC-02,2001-125,NaN,0.85
114,40009,621-1544,CRAIG COUNTY COURT,24-DEC-02,1999-84,NaN,0.85
115,40009,621-1544,CRAIG COUNTY COURT,05-NOV-01,1999-84,NaN,9.00
116,40009,721-701.7,COTTON COUNTY COURT,07-JUN-01,1999-46,8888.0,NaN
117,40009,863-2-402,PITTSBURG COUNTY COURT,29-JUN-01,2001-222B,NaN,3.00
118,40009,863-2-402,PITTSBURG COUNTY COURT,29-JUN-01,2001-222B,NaN,3.00
119,40009,863-2-402,PITTSBURG COUNTY COURT,29-JUN-01,2001-222B,NaN,3.00
120,40009,847-4-102,ATOKA COUNTY COURT,04-OCT-04,2004-73,NaN,2.00
121,40009,847-4-102,ATOKA COUNTY COURT,05-DEC-07,2004-73,5.0,NaN
122,40009,821-1550.28,ATOKA COUNTY COURT,05-DEC-07,2007-148,3.0,NaN
123,40009,821-1541.1,ATOKA COUNTY COURT,05-DEC-07,2007-148,1.0,NaN
124,40009,821-1541.1,ATOKA COUNTY COURT,05-DEC-07,2007-148,1.0,NaN
125,40009,821-1541.1,ATOKA COUNTY COURT,05-DEC-07,2007-148,1.0,NaN
126,40009,821-1705,PITTSBURG COUNTY COURT,14-JAN-08,2007-464,5.0,NaN
127,40009,863-2-402,ATOKA COUNTY COURT,25-JAN-07,2007-148,NaN,5.00
128,40009,921-1115,COTTON COUNTY COURT,21-MAY-01,2000-20,50.0,NaN
129,40009,921-1115,COTTON COUNTY COURT,21-MAY-01,2000-20,50.0,NaN
130,40010,063-2-402,COTTON COUNTY COURT,18-JUN-01,2000-60,2.0,3.00
131,40010,063-2-402,COTTON COUNTY COURT,29-APR-02,2000-60,NaN,4.14
132,40010,063-2-402,COTTON COUNTY COURT,18-JUN-01,2000-60,NaN,5.00

Schedule D - Offense Codes Layout
=======================================================
 ```
 Name                            Null?    Type
 ------------------------------- -------- ----
 STATUTE_CODE                    NOT NULL VARCHAR2(38)
 DESCRIPTION                     NOT NULL VARCHAR2(40)
 VIOLENT                                  VARCHAR2(1)
```

In [6]:
file = 'data/odoc/Vendor_Offense_Extract_Text.dat'

names = ["STATUTE_CODE",
         "DESCRIPTION", 
         "VIOLENT",
]

widths = [
    38,
    40,
    1
]

df = pd.read_fwf(file, 
    header=None,
    widths=widths,
    names=names)
                 
df

       STATUTE_CODE                               DESCRIPTION VIOLENT
0               0-0               UNKNOWN - FOR WARRANTS ONLY       N
1           10-1144         ACTS CAUSING JUVENILE DELINQUENCY       N
2           10-1627             DEPRIVATION OF LAWFUL CUSTODY       N
3             10-26   UNLAWFUL ASSUMPTION OF CUSTODY OF CHILD       N
4          10-404.1  SEX OFFENDER PROVIDING SERVICES TO CHILD       N
5            10-410  OPERATING CHILD CARE FACILITY W/O LICENS       N
6             10-71                       PATERNITY COMPLAINT       N
7           10-7103                   FAILURE TO REPORT CHILD       N
8           10-7115                               CHILD ABUSE       Y
9      10-7303-1.1B  REFUSE TO ASSUME CUSTODY OF CHILD IN DET       N
10    10A-2-7-611.B      PROHIBITED ITEMS JUVENILE FACILITIES       N
11         13-176.3      VIOLATING SECURITY OF COMMUNICATIONS       N
12       13-176.3.8    UNLAWFUL USE OF COMMUNICATION FACILITY       N
13         13-176.7   USE OF COMMUNICATION FACILITY TO COMMIT       N
14           15-751         CONSUMER PROTECTION ACT VIOLATION       N
15           15-753         CONSUMER PROTECTION ACT VIOLATION       N
16         15-765.3                         HOME REPAIR FRAUD       N
17           15-767      CONDUCT CLOSING OUT SALE W/O LICENSE       N
18        18-1020.F  CORP. FAILING TO FILE REAL ESTATE STATEM       N
19        18-552.11         FRAUDULENT USE OF NAME IN CHARITY       N
20        18-552.18  UNLAWFUL SOLICIT CHARITABLE CONTRIBUTION       N
21         18-553.3   FAILURE TO REGISTER AS PROF FUND RAISER       N
22           18-951  FOREIGN CORPORATION ENGAGED IN FARMING/R       N
23          19-1610            TRANSIENT MERCHANT W/O LICENSE       N
24           19-641              EMBEZZLEMENT OF PUBLIC MONEY       N
25           19-682  COUNTY OFF/FAILING TO MAKE DAILY DEPOSIT       N
26        19-863.28                          ZONING VIOLATION       N
27        19-863.45  VIOLATION OF COUNTY BLDG/INSP/RULES & RE       N
28        19-863.48                   MOVING HOUSE W/O PERMIT       N
29        19-865.67                   COUNTY ZONING VIOLATION       N
...             ...                                       ...     ...
1145         68-412                     TOBACCO TAX VIOLATION       N
1146         68-418                    POSS UNSTAMPED TOBACCO       N
1147       68-450.8       FAILURE TO DISPLAY TAX STAMP ON CDS       N
1148         68-506          EMBEZZLEMENT OF MOTOR FUEL TAXES       N
1149        69-1211    CONSTRUCTION OF STATE/FED RIGHT-OF-WAY       N
1150        69-1213           OBSTRUCTING PUBLIC RIGHT OF WAY       N
1151      69-1213.A   DAMAGE OR REMOVE TRAFFIC CONTROL DEVICE       N
1152         7-19.1   DENIAL OF SERVICES TO BLIND W/GUIDE DOG       N
1153       70-1-105                  COMPULSORY EDUCATION ACT       N
1154      70-24-131         REFUSING TO LEAVE SCHOOL PREMISES       N
1155         71-101                          SECURITIES FRAUD       N
1156         71-201     ACTING AS REGISTERED SECURITIES AGENT       N
1157         71-301           SELLING UNREGISTERED SECURITIES       N
1158         71-402    UNLAWFUL DIST OF SECURITIES LITERATURE       N
1159         71-823    VIOLATE BUSINESS OPPORTUNITY SALES ACT       N
1160        74-1812          UNLAWFUL USE OF MV IN STATE PARK       N
1161      74-1846.1   ALLOWING DOG TO RUN LOOSE AT STATE PARK       N
1162      74-1846.2  INJURY TO STRUCTURE/TREES ETC. AT ST PAR       N
1163      74-1847.1  VIOLATION OF ST PARK RULES AND REGULATIO       N
1164        74-3404                 MAKING/RECEIVING KICKBACK       N
1165        74-4211    FAILURE TO FILE CAMPAIGN CONTRIBUTIONS       N
1166        74-4220             ANONYMOUS CAMPAIGN LITERATURE       N
1167        74-4221  VIOL OF CAMPAIGN & ETHICAL STANDARDS ACT       N
1168      74-841.23              VIOLATION STATE MERIT SYSTEM       N
1169        74-85.7   EVADING COMPETITIVE BID/SPLIT PURCHASES       N
1170         74-924  FILE FALSE STATEMENT PUBLIC EMPLOYEE RET       N
1171          76-23                  TAMPERING WITH UTILITIES       N
1172     82-1020.22   VIOLATION OF WATER RESOURCES RULES/REGS       N
1173       82-105.2                 UNAUTHORIZED USE OF WATER       N
1174        82-1455             LITTERING A SCENIC RIVER AREA       N

[1175 rows x 3 columns]