In [1]:
import csv
import sys
import pandas as pd

from datetime import datetime

def make_date (myDate):
    year = myDate.split("-")
    if int(year[0]) < 2261:
        dt = datetime.strptime(myDate, "%Y-%m-%d 00:00:00")
        return dt
    else:
        print("year too big for Pandas", year[0])
        raise ValueError('Invalid date')

In [ ]:
csv.field_size_limit(sys.maxsize)
sentence_database = []
first_row = 0
myRange = [5, 15, 16]

with open('OffenderSentence.csv', encoding = "ISO-8859-1") as csvfile:
    offender_reader = csv.reader(csvfile, delimiter=',')
    for row in offender_reader:
        if first_row == 0:
            print(row)
            first_row = row
        else:
            try:
                for i in myRange:
                    #print(i, row[i])
                    row[i] = make_date(row[i])
            except:
                continue
            sentence_database.append(row)

['Id', 'DOCNum', 'OrderID', 'ChargeSeq', 'CRFNum', 'ConvictDate', 'Court', 'StatuteCode', 'OffenceDescription', 'OffenceComment', 'SentenceTermCode', 'Years', 'Months', 'Days', 'SentenceTerm', 'StartDate', 'EndDate', 'CountNum', 'OrderCode', 'ConsecutiveToCount', 'ChargeStatus']
year too big for Pandas 2272
year too big for Pandas 2984
year too big for Pandas 2890
year too big for Pandas 3004
year too big for Pandas 2861
year too big for Pandas 2986
year too big for Pandas 2381
year too big for Pandas 2530
year too big for Pandas 2430
year too big for Pandas 2680
year too big for Pandas 2992
year too big for Pandas 3006
year too big for Pandas 2973
year too big for Pandas 2972
year too big for Pandas 2996
year too big for Pandas 2996
year too big for Pandas 2981
year too big for Pandas 2341
year too big for Pandas 2341
year too big for Pandas 2491
year too big for Pandas 2611
year too big for Pandas 2761
year too big for Pandas 2801
year too big for Pandas 2841
year too big for Pandas 2881
year too big for Pandas 2921
year too big for Pandas 2961
year too big for Pandas 3001
year too big for Pandas 3041
year too big for Pandas 3081
year too big for Pandas 3121
year too big for Pandas 3161
year too big for Pandas 3201
year too big for Pandas 3501
year too big for Pandas 3801
year too big for Pandas 2997
year too big for Pandas 2992
year too big for Pandas 2983
year too big for Pandas 2348
year too big for Pandas 2952
year too big for Pandas 2976
year too big for Pandas 2965
year too big for Pandas 2673
year too big for Pandas 2480
year too big for Pandas 2480
year too big for Pandas 2540
year too big for Pandas 2490
year too big for Pandas 2480
year too big for Pandas 2895
year too big for Pandas 2895
year too big for Pandas 2264
year too big for Pandas 2264
year too big for Pandas 3966
year too big for Pandas 2985
year too big for Pandas 2985
year too big for Pandas 2862
year too big for Pandas 2862
year too big for Pandas 3056
year too big for Pandas 2470
year too big for Pandas 3963
year too big for Pandas 2377
year too big for Pandas 2961
year too big for Pandas 2281
year too big for Pandas 2399
year too big for Pandas 3046
year too big for Pandas 3046
year too big for Pandas 2311
year too big for Pandas 2311
year too big for Pandas 2300
year too big for Pandas 3025
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3036
year too big for Pandas 3977
year too big for Pandas 2991
year too big for Pandas 3973
year too big for Pandas 3044
year too big for Pandas 3044
year too big for Pandas 3044
year too big for Pandas 3205
year too big for Pandas 3963
year too big for Pandas 2911
year too big for Pandas 2401
year too big for Pandas 2989
year too big for Pandas 2992
year too big for Pandas 2992
year too big for Pandas 3991
year too big for Pandas 4990
year too big for Pandas 5989
year too big for Pandas 6988
year too big for Pandas 3961
year too big for Pandas 3976
year too big for Pandas 3135
year too big for Pandas 2990
year too big for Pandas 2991
year too big for Pandas 2992
year too big for Pandas 3035
year too big for Pandas 3035
year too big for Pandas 3004
year too big for Pandas 3004
year too big for Pandas 3020
year too big for Pandas 2787
year too big for Pandas 2895
year too big for Pandas 2898
year too big for Pandas 2753
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 2993
year too big for Pandas 2995
year too big for Pandas 2889
year too big for Pandas 3972
year too big for Pandas 3036
year too big for Pandas 3973
year too big for Pandas 3046
year too big for Pandas 3046
year too big for Pandas 3976
year too big for Pandas 2799
year too big for Pandas 2799
year too big for Pandas 3742
year too big for Pandas 5743
year too big for Pandas 7745
year too big for Pandas 6988
year too big for Pandas 8074
year too big for Pandas 8576
year too big for Pandas 3742
year too big for Pandas 3039
year too big for Pandas 3039
year too big for Pandas 2799
year too big for Pandas 2799
year too big for Pandas 2799
year too big for Pandas 2799
year too big for Pandas 2301
year too big for Pandas 2301
year too big for Pandas 2401
year too big for Pandas 2501
year too big for Pandas 2599
year too big for Pandas 2649
year too big for Pandas 2998
year too big for Pandas 2998
year too big for Pandas 2998
year too big for Pandas 3997
year too big for Pandas 3978
year too big for Pandas 2299
year too big for Pandas 2299
year too big for Pandas 2299
year too big for Pandas 2717
year too big for Pandas 2721
year too big for Pandas 2887
year too big for Pandas 2792
year too big for Pandas 3980
year too big for Pandas 3980
year too big for Pandas 2908
year too big for Pandas 2908
year too big for Pandas 2264
year too big for Pandas 2264
year too big for Pandas 2264
year too big for Pandas 2264
year too big for Pandas 2309
year too big for Pandas 2309
year too big for Pandas 2354
year too big for Pandas 2354
year too big for Pandas 2354
year too big for Pandas 2399
year too big for Pandas 2995
year too big for Pandas 3977
year too big for Pandas 3978
year too big for Pandas 3112
year too big for Pandas 2995
year too big for Pandas 2995
year too big for Pandas 3495
year too big for Pandas 5245
year too big for Pandas 6244
year too big for Pandas 7243
year too big for Pandas 8242
year too big for Pandas 8737
year too big for Pandas 8757
year too big for Pandas 8777
year too big for Pandas 8817
year too big for Pandas 8837
year too big for Pandas 9337
year too big for Pandas 2909
year too big for Pandas 2426
year too big for Pandas 2426
year too big for Pandas 2426
year too big for Pandas 2426
year too big for Pandas 2292
year too big for Pandas 2292
year too big for Pandas 2367
year too big for Pandas 2382
year too big for Pandas 2402
year too big for Pandas 3976
year too big for Pandas 2274
year too big for Pandas 2806
year too big for Pandas 2804
year too big for Pandas 2900
year too big for Pandas 2900
year too big for Pandas 2886
year too big for Pandas 2997
year too big for Pandas 2998
year too big for Pandas 3053
year too big for Pandas 3053
year too big for Pandas 3006
year too big for Pandas 2994
year too big for Pandas 2996
year too big for Pandas 2997
year too big for Pandas 2960
year too big for Pandas 3032
year too big for Pandas 3032
year too big for Pandas 2401
year too big for Pandas 2998
year too big for Pandas 3023
year too big for Pandas 3023
year too big for Pandas 3023
year too big for Pandas 3023
year too big for Pandas 3023
year too big for Pandas 3023
year too big for Pandas 3027
year too big for Pandas 2275
year too big for Pandas 2275
year too big for Pandas 2295
year too big for Pandas 2315
year too big for Pandas 2335
year too big for Pandas 2355
year too big for Pandas 2375
year too big for Pandas 2395
year too big for Pandas 2415
year too big for Pandas 2435
year too big for Pandas 2455
year too big for Pandas 2475
year too big for Pandas 2495
year too big for Pandas 2515
year too big for Pandas 2535
year too big for Pandas 2555
year too big for Pandas 2575
year too big for Pandas 2595
year too big for Pandas 2615
year too big for Pandas 2635
year too big for Pandas 2572
year too big for Pandas 2572
year too big for Pandas 2572
year too big for Pandas 2672
year too big for Pandas 2672
year too big for Pandas 3272
year too big for Pandas 2295
year too big for Pandas 2340
year too big for Pandas 2906
year too big for Pandas 3001
year too big for Pandas 3034
year too big for Pandas 3009
year too big for Pandas 3005
year too big for Pandas 3005
year too big for Pandas 3005
year too big for Pandas 3005
year too big for Pandas 3030
year too big for Pandas 2479
year too big for Pandas 2478
year too big for Pandas 2478
year too big for Pandas 2473
year too big for Pandas 3049
year too big for Pandas 3049
year too big for Pandas 3049
year too big for Pandas 3049
year too big for Pandas 3049
year too big for Pandas 3049
year too big for Pandas 3049
year too big for Pandas 3049
year too big for Pandas 3040
year too big for Pandas 9999
year too big for Pandas 3009
year too big for Pandas 3120
year too big for Pandas 3120
year too big for Pandas 2991

year too big for Pandas 2290
year too big for Pandas 2290
year too big for Pandas 2295
year too big for Pandas 2320
year too big for Pandas 2330
year too big for Pandas 2400
year too big for Pandas 2350
year too big for Pandas 2400
year too big for Pandas 2355
year too big for Pandas 2410
year too big for Pandas 2365
year too big for Pandas 2430
year too big for Pandas 2385
year too big for Pandas 2430
year too big for Pandas 2395
year too big for Pandas 2440
year too big for Pandas 2405
year too big for Pandas 2450
year too big for Pandas 2425
year too big for Pandas 2470
year too big for Pandas 2445
year too big for Pandas 2490
year too big for Pandas 2465
year too big for Pandas 2510
year too big for Pandas 2475
year too big for Pandas 2530
year too big for Pandas 2495
year too big for Pandas 2545
year too big for Pandas 2505
year too big for Pandas 2565
year too big for Pandas 2525
year too big for Pandas 2585
year too big for Pandas 2575
year too big for Pandas 2595
year too big for Pandas 2725
year too big for Pandas 2615
year too big for Pandas 2745
year too big for Pandas 2635
year too big for Pandas 2765
year too big for Pandas 2655
year too big for Pandas 2785
year too big for Pandas 2675
year too big for Pandas 3030
year too big for Pandas 3030
year too big for Pandas 3000
year too big for Pandas 3006
year too big for Pandas 3006
year too big for Pandas 3022
year too big for Pandas 3022
year too big for Pandas 3000
year too big for Pandas 9999
year too big for Pandas 3094

In [3]:
sentenceDS = pd.DataFrame(data=sentence_database, columns=first_row)

In [8]:
pd.pivot_table(sentenceDS, values=["DOCNum"], index=["SentenceTermCode"], aggfunc="count")

                  DOCNum
SentenceTermCode
                    3001
12-Month Review       24
CSD Accerated         96
CSD Deferred        5840
CSD Revocation        59
CSD Suspended      21311
CSD-Disc. Sanc.       28
CSD-General Mod       27
CSDDIS                 4
CSDDIS-S               2
Cor. Compact         152
Death                276
Delayed             1091
Drug Court         13573
Incarceration     564318
Int Parole In       1272
Int. Parole         4592
Int. Prob. In       2106
Int. Probation      7767
Life                4905
Life w/o Parole     1248
Minimum            10587
P&PDEF             41979
P&PSUS            205804
PIS                 6370
Parole             34819
Pre-Release Sup    16115
Probation         328144

In [18]:
sentenceDS[sentenceDS.SentenceTermCode == ""].pivot_table(values=["DOCNum"], index=["SentenceTerm"], aggfunc="count")

                DOCNum
SentenceTerm
                  1702
-1 Y 1 M 12 D        1
-1 Y 1 M 8 D         1
-1 Y 11 M 12 D       1
-1 Y 11 M 21 D       1
-1 Y 11 M 25 D       1
-1 Y 11 M 28 D       1
-1 Y 11 M 30 D       1
-1 Y 6 M 25 D        2
-1 Y 7 M 9 D         1
-1 Y 8 M 9 D         1
-2 Y 10 M 14 D       1
-2 Y 3 M             1
-2 Y 6 M             2
-2 Y 8 M 8 D         1
-3 Y 5 M 11 D        1
-3 Y 6 M 13 D        1
-4 Y 9 M 13 D        1
-7 Y 7 M 20 D        1
-93 Y 3 M 2 D        1
1 D                 16
1 M                  3
1 M 13 D             2
1 M 14 D             1
1 M 18 D             2
1 M 20 D             1
1 M 21 D             1
1 M 22 D             1
1 M 27 D             2
1 M 28 D             1
...                ...
95 Y 4 M 9 D         1
95 Y 5 M 14 D        1
95 Y 6 D             1
96 Y 11 M 5 D        1
96 Y 2 M 22 D        4
96 Y 2 M 28 D        1
96 Y 26 D            1
96 Y 3 M 26 D        1
97 Y 1 M 27 D        1
97 Y 10 M 19 D       1
97 Y 10 M 26 D       1
97 Y 3 M 16 D        1
97 Y 3 M 17 D        1
97 Y 5 M 25 D        1
97 Y 7 M 21 D        2
97 Y 9 M 30 D        1
98 Y 2 M 13 D        1
98 Y 4 M 27 D        1
98 Y 5 D             1
98 Y 5 M 10 D        1
98 Y 8 M 2 D         1
98 Y 8 M 29 D        1
98 Y 9 M 18 D        1
99 Y 21 D            1
99 Y 3 M 22 D        1
99 Y 4 M 13 D        1
99 Y 4 M 16 D        1
99 Y 8 M 29 D        1
DEATH                2
LIFE                 9

[834 rows x 1 columns]