In [1]:
import csv
import sys
import pandas as pd

csv.field_size_limit(sys.maxsize)
sentence_database = []
first_row = 0

with open('OffenderSentence.csv', encoding = "ISO-8859-1") as csvfile:
    offender_reader = csv.reader(csvfile, delimiter=',')
    for row in offender_reader:
        if first_row == 0:
            print(row)
            first_row = row
        else:
            sentence_database.append(row)

['Id', 'DOCNum', 'OrderID', 'ChargeSeq', 'CRFNum', 'ConvictDate', 'Court', 'StatuteCode', 'OffenceDescription', 'OffenceComment', 'SentenceTermCode', 'Years', 'Months', 'Days', 'SentenceTerm', 'StartDate', 'EndDate', 'CountNum', 'OrderCode', 'ConsecutiveToCount', 'ChargeStatus']

In [3]:
sentenceDS = pd.DataFrame(data=sentence_database, columns=first_row)

In [8]:
pd.pivot_table(sentenceDS, values=["DOCNum"], index=["SentenceTermCode"], aggfunc="count")

                  DOCNum
SentenceTermCode
                    3001
12-Month Review       24
CSD Accerated         96
CSD Deferred        5840
CSD Revocation        59
CSD Suspended      21311
CSD-Disc. Sanc.       28
CSD-General Mod       27
CSDDIS                 4
CSDDIS-S               2
Cor. Compact         152
Death                276
Delayed             1091
Drug Court         13573
Incarceration     564318
Int Parole In       1272
Int. Parole         4592
Int. Prob. In       2106
Int. Probation      7767
Life                4905
Life w/o Parole     1248
Minimum            10587
P&PDEF             41979
P&PSUS            205804
PIS                 6370
Parole             34819
Pre-Release Sup    16115
Probation         328144

In [18]:
sentenceDS[sentenceDS.SentenceTermCode == ""].pivot_table(values=["DOCNum"], index=["SentenceTerm"], aggfunc="count")

                DOCNum
SentenceTerm
                  1702
-1 Y 1 M 12 D        1
-1 Y 1 M 8 D         1
-1 Y 11 M 12 D       1
-1 Y 11 M 21 D       1
-1 Y 11 M 25 D       1
-1 Y 11 M 28 D       1
-1 Y 11 M 30 D       1
-1 Y 6 M 25 D        2
-1 Y 7 M 9 D         1
-1 Y 8 M 9 D         1
-2 Y 10 M 14 D       1
-2 Y 3 M             1
-2 Y 6 M             2
-2 Y 8 M 8 D         1
-3 Y 5 M 11 D        1
-3 Y 6 M 13 D        1
-4 Y 9 M 13 D        1
-7 Y 7 M 20 D        1
-93 Y 3 M 2 D        1
1 D                 16
1 M                  3
1 M 13 D             2
1 M 14 D             1
1 M 18 D             2
1 M 20 D             1
1 M 21 D             1
1 M 22 D             1
1 M 27 D             2
1 M 28 D             1
...                ...
95 Y 4 M 9 D         1
95 Y 5 M 14 D        1
95 Y 6 D             1
96 Y 11 M 5 D        1
96 Y 2 M 22 D        4
96 Y 2 M 28 D        1
96 Y 26 D            1
96 Y 3 M 26 D        1
97 Y 1 M 27 D        1
97 Y 10 M 19 D       1
97 Y 10 M 26 D       1
97 Y 3 M 16 D        1
97 Y 3 M 17 D        1
97 Y 5 M 25 D        1
97 Y 7 M 21 D        2
97 Y 9 M 30 D        1
98 Y 2 M 13 D        1
98 Y 4 M 27 D        1
98 Y 5 D             1
98 Y 5 M 10 D        1
98 Y 8 M 2 D         1
98 Y 8 M 29 D        1
98 Y 9 M 18 D        1
99 Y 21 D            1
99 Y 3 M 22 D        1
99 Y 4 M 13 D        1
99 Y 4 M 16 D        1
99 Y 8 M 29 D        1
DEATH                2
LIFE                 9

[834 rows x 1 columns]